[workspace]

members = [
  "client",
  "server",
  "signal",
  "udp-server",
  "udp-client",
  "ortc-client",
  "ortc-server",
]

resolver = "2"

[patch.crates-io]
webrtc = { path  = "../webrtc/webrtc" }